export const commoditiesData = [
  // --- MILE 12 MARKET ---
  {
    id: 1,
    title: "Tomatoes",
    snippet: "Big Basket",
    unit: "25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 45000,
    trend: 8.2,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T08:30:00Z",
    userId: "system", // Internal data
    status: "Verified",
  },
  {
    id: 2,
    title: "Rice",
    snippet: "Bag",
    unit: "50kg",
    image: "/images/rice.svg",
    source: "verified",
    price: 82000,
    trend: 5.4,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T09:10:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 3,
    title: "Garri",
    snippet: "Paint Bucket",
    unit: "5kg",
    image: "/images/garri.svg",
    source: "crowdsourced",
    price: 3500,
    trend: 3.1,
    trendDirection: "down",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T07:45:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 4,
    title: "Beans",
    snippet: "Mudu",
    unit: "3kg",
    image: "/images/beans.svg",
    source: "verified",
    price: 7200,
    trend: 12.0,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 5,
    title: "Palm Oil",
    snippet: "kerosene keg -20l",
    unit: "1kg",
    image: "/images/palmoil.svg",
    source: "verified",
    price: 28500,
    trend: 7.8,
    trendDirection: "up",
    category: "Oil",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 6,
    title: "Onions",
    snippet: "Medium Bag",
    unit: "10kg",
    image: "/images/onions.svg",
    source: "crowdsourced",
    price: 18000,
    trend: 4.5,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 7,
    title: "Yam",
    snippet: "Per Tuber",
    unit: "3kg",
    image: "/images/yam.svg",
    source: "verified",
    price: 2800,
    trend: 2.3,
    trendDirection: "up",
    category: "Tubers",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 8,
    title: "Pepper",
    snippet: "Derica",
    unit: "1.5kg",
    image: "/images/pepper.svg",
    source: "crowdsourced",
    price: 4500,
    trend: 6.7,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 14,
    title: "Wheat",
    snippet: "Bag",
    unit: "50kg",
    image: "/images/wheat.jpg",
    source: "verified",
    price: 42000,
    trend: 1.2,
    trendDirection: "down",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T12:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 15,
    title: "Eggs",
    snippet: "Crate of 30",
    unit: "1kg",
    image: "/images/eggs.jpg",
    source: "verified",
    price: 5500,
    trend: 10.5,
    trendDirection: "up",
    category: "Protein",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T13:00:00Z",
    userId: "system",
    status: "Verified",
  },

  // --- Agege MARKET ---
  {
    id: 9,
    title: "Maize",
    snippet: "Mudu",
    unit: "2kg",
    image: "/images/maize.svg",
    source: "verified",
    price: 1200,
    trend: 2.1,
    trendDirection: "down",
    category: "Grains",
    market: "Agege Market",
    createdAt: "2026-03-27T08:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 10,
    title: "Sweet Potatoes",
    snippet: "Small Basket",
    unit: "1kg",
    image: "/images/potatoes.jpg",
    source: "crowdsourced",
    price: 5000,
    trend: 1.5,
    trendDirection: "up",
    category: "Tubers",
    market: "Agege Market",
    createdAt: "2026-03-27T09:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 16,
    title: "Soya Beans",
    snippet: "Mudu",
    unit: "2kg",
    image: "/images/soyabeans.jpg",
    source: "verified",
    price: 2500,
    trend: 3.0,
    trendDirection: "up",
    category: "Grains",
    market: "Agege Market",
    createdAt: "2026-03-27T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 17,
    title: "Plantain Flour",
    snippet: "Pack",
    unit: "1kg",
    image: "/images/plantain-flour.jpg",
    source: "verified",
    price: 3200,
    trend: 0.5,
    trendDirection: "down",
    category: "Tubers",
    market: "Agege Market",
    createdAt: "2026-03-27T11:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 18,
    title: "Honey",
    snippet: "Bottle",
    unit: "1L",
    image: "/images/honey.jpg",
    source: "crowdsourced",
    price: 6500,
    trend: 2.2,
    trendDirection: "up",
    category: "Oil",
    market: "Agege Market",
    createdAt: "2026-03-27T12:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 19,
    title: "Melon (Egusi)",
    snippet: "Mudu",
    unit: "1kg",
    image: "/images/eguisi.jpg",
    source: "verified",
    price: 4500,
    trend: 1.8,
    trendDirection: "down",
    category: "Grains",
    market: "Agege Market",
    createdAt: "2026-03-27T13:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 20,
    title: "Dry Fish",
    unit: "1kg",
    snippet: "Medium Size",
    image: "/images/fish.jpg",
    source: "crowdsourced",
    price: 2000,
    trend: 5.0,
    trendDirection: "up",
    category: "Protein",
    market: "Agege Market",
    createdAt: "2026-03-27T14:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 21,
    title: "Crayfish",
    unit: "1kg",
    snippet: "Large Paint Bucket",
    image: "/images/crayfish.jpg",
    source: "verified",
    price: 18000,
    trend: 9.2,
    trendDirection: "up",
    category: "Protein",
    market: "Agege Market",
    createdAt: "2026-03-27T15:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 22,
    title: "Charcoal",
    snippet: "Large Bag",
    unit: "1kg",
    image: "/images/charcoal.jpg",
    source: "verified",
    price: 9000,
    trend: 0.0,
    trendDirection: "down",
    category: "All",
    market: "Agege Market",
    createdAt: "2026-03-27T16:00:00Z",
    userId: "system",
    status: "Verified",
  },

  // --- Agbalata Market Badagry ---
  {
    id: 11,
    title: "Beef",
    snippet: "Fresh Cut",
    unit: "1kg",
    image: "/images/beef.jpg",
    source: "verified",
    price: 6000,
    trend: 4.2,
    trendDirection: "up",
    category: "Protein",
    market: "Agbalata Market Badagry",
    createdAt: "2026-03-27T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 12,
    title: "Vegetable Oil",
    snippet: "Gallon",
    unit: "5l",
    image: "/images/vegetable-oil.jpg",
    source: "verified",
    price: 12500,
    trend: 0.5,
    trendDirection: "down",
    category: "Oil",
    market: "Agbalata Market Badagry",
    createdAt: "2026-03-27T11:00:00Z",
    userId: "system",
    status: "Verified",
  },

  // --- Mushin Market ---
  {
    id: 13,
    title: "Plantain",
    snippet: "Large Bunch",
    unit: "1kg",
    image: "/images/plantain.jpg",
    source: "crowdsourced",
    price: 4000,
    trend: 15.0,
    trendDirection: "up",
    category: "Tubers",
    market: "Mushin Market",
    createdAt: "2026-03-27T12:00:00Z",
    userId: "system",
    status: "Verified",
  },
];
