export const priceHistory = [
  // --- MILE 12 MARKET (Lagos) ---
  {
    id: 1,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 45000,
    trend: 8.2,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T08:30:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 23,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 41500,
    trend: 2.1,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-01T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 24,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 43000,
    trend: 3.6,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-05T09:15:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 25,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 42000,
    trend: 2.3,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-08T11:30:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 26,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 46500,
    trend: 10.7,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-12T08:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 27,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 48000,
    trend: 3.2,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-15T14:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 28,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "crowdsourced",
    price: 47000,
    trend: 2.1,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-18T10:45:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 29,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 44000,
    trend: 6.3,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-22T09:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 30,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 45500,
    trend: 3.4,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-25T08:30:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 31,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 45000,
    trend: 1.1,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-28T12:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 32,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 43500,
    trend: 3.3,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-04-02T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 2,
    title: "Rice",
    snippet: "50kg Bag",
    image: "/images/rice.svg",
    source: "verified",
    price: 82000,
    trend: 5.2,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T09:10:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 120,
    title: "Rice",
    snippet: "50kg Bag",
    image: "/images/rice.svg",
    source: "verified",
    price: 85000,
    trend: 5.4,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-27T08:11:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 121,
    title: "Rice",
    snippet: "50kg Bag",
    image: "/images/rice.svg",
    source: "verified",
    price: 83000,
    trend: 5.1,
    trendDirection: "down",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-28T08:11:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 122,
    title: "Rice",
    snippet: "50kg Bag",
    image: "/images/rice.svg",
    source: "verified",
    price: 85000,
    trend: 5.2,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-28T08:11:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 3,
    title: "Garri",
    snippet: "Paint Bucket ~5kg",
    image: "/images/garri.svg",
    source: "crowdsourced",
    price: 3500,
    trend: 3.1,
    trendDirection: "down",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T07:45:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 123,
    title: "Garri",
    snippet: "Paint Bucket ~5kg",
    image: "/images/garri.svg",
    source: "verified",
    price: 3800,
    trend: 8.5,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-20T09:15:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 124,
    title: "Garri",
    snippet: "Paint Bucket ~5kg",
    image: "/images/garri.svg",
    source: "verified",
    price: 3650,
    trend: 3.9,
    trendDirection: "down",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-15T11:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 125,
    title: "Garri",
    snippet: "Paint Bucket ~5kg",
    image: "/images/garri.svg",
    source: "crowdsourced",
    price: 4000,
    trend: 9.6,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-10T08:30:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 126,
    title: "Garri",
    snippet: "Paint Bucket ~5kg",
    image: "/images/garri.svg",
    source: "verified",
    price: 3400,
    trend: 15.0,
    trendDirection: "down",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-05T14:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 4,
    title: "Beans",
    snippet: "Mudu ~3kg",
    image: "/images/beans.svg",
    source: "verified",
    price: 7200,
    trend: 12.0,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 5,
    title: "Palm Oil",
    snippet: "kerosene keg -20l",
    image: "/images/palmoil.svg",
    source: "verified",
    price: 28500,
    trend: 7.8,
    trendDirection: "up",
    category: "Oil",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 6,
    title: "Onions",
    snippet: "Medium Bag ~10kg",
    image: "/images/onions.svg",
    source: "crowdsourced",
    price: 18000,
    trend: 4.5,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 7,
    title: "Yam",
    snippet: "Per Tuber ~3kg",
    image: "/images/yam.svg",
    source: "verified",
    price: 2800,
    trend: 2.3,
    trendDirection: "up",
    category: "Tubers",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 8,
    title: "Pepper",
    snippet: "Derica ~1.5kg",
    image: "/images/pepper.svg",
    source: "crowdsourced",
    price: 4500,
    trend: 6.7,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 14,
    title: "Wheat",
    snippet: "50kg Bag",
    image: "/images/wheat.jpg",
    source: "verified",
    price: 42000,
    trend: 1.2,
    trendDirection: "down",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T12:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 15,
    title: "Eggs",
    snippet: "Crate of 30",
    image: "/images/eggs.jpg",
    source: "verified",
    price: 5500,
    trend: 10.5,
    trendDirection: "up",
    category: "Protein",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T13:00:00Z",
    userId: "system",
    status: "Verified",
  },

  // --- Agege Market ---
  {
    id: 9,
    title: "Maize",
    snippet: "Mudu ~2kg",
    image: "/images/maize.svg",
    source: "verified",
    price: 1200,
    trend: 2.1,
    trendDirection: "down",
    category: "Grains",
    market: "Agege Market",
    createdAt: "2026-03-27T08:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 10,
    title: "Sweet Potatoes",
    snippet: "Small Basket",
    image: "/images/potatoes.jpg",
    source: "crowdsourced",
    price: 5000,
    trend: 1.5,
    trendDirection: "up",
    category: "Tubers",
    market: "Agege Market",
    createdAt: "2026-03-27T09:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 16,
    title: "Soya Beans",
    snippet: "Mudu ~2kg",
    image: "/images/soyabeans.jpg",
    source: "verified",
    price: 2500,
    trend: 3.0,
    trendDirection: "up",
    category: "Grains",
    market: "Agege Market",
    createdAt: "2026-03-27T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 17,
    title: "Plantain Flour",
    snippet: "1kg Pack",
    image: "/images/plantain-flour.jpg",
    source: "verified",
    price: 3200,
    trend: 0.5,
    trendDirection: "down",
    category: "Tubers",
    market: "Agege Market",
    createdAt: "2026-03-27T11:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 18,
    title: "Honey",
    snippet: "1L Bottle",
    image: "/images/honey.jpg",
    source: "crowdsourced",
    price: 6500,
    trend: 2.2,
    trendDirection: "up",
    category: "Oil",
    market: "Agege Market",
    createdAt: "2026-03-27T12:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 19,
    title: "Melon (Egusi)",
    snippet: "Mudu",
    image: "/images/eguisi.jpg",
    source: "verified",
    price: 4500,
    trend: 1.8,
    trendDirection: "down",
    category: "Grains",
    market: "Agege Market",
    createdAt: "2026-03-27T13:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 20,
    title: "Dry Fish",
    snippet: "Medium Size",
    image: "/images/fish.jpg",
    source: "crowdsourced",
    price: 2000,
    trend: 5.0,
    trendDirection: "up",
    category: "Protein",
    market: "Agege Market",
    createdAt: "2026-03-27T14:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 21,
    title: "Crayfish",
    snippet: "Large Paint Bucket",
    image: "/images/crayfish.jpg",
    source: "verified",
    price: 18000,
    trend: 9.2,
    trendDirection: "up",
    category: "Protein",
    market: "Agege Market",
    createdAt: "2026-03-27T15:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 22,
    title: "Charcoal",
    snippet: "Large Bag",
    image: "/images/charcoal.jpg",
    source: "verified",
    price: 9000,
    trend: 0.0,
    trendDirection: "down",
    category: "All",
    market: "Agege Market",
    createdAt: "2026-03-27T16:00:00Z",
    userId: "system",
    status: "Verified",
  },

  // --- Agbalata Market Badagry ---
  {
    id: 11,
    title: "Beef",
    snippet: "1kg Fresh Cut",
    image: "/images/beef.jpg",
    source: "verified",
    price: 6000,
    trend: 4.2,
    trendDirection: "up",
    category: "Protein",
    market: "Agbalata Market Badagry",
    createdAt: "2026-03-27T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 12,
    title: "Vegetable Oil",
    snippet: "5L Gallon",
    image: "/images/vegetable-oil.jpg",
    source: "verified",
    price: 12500,
    trend: 0.5,
    trendDirection: "down",
    category: "Oil",
    market: "Agbalata Market Badagry",
    createdAt: "2026-03-27T11:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 110,
    title: "Rice",
    snippet: "50kg Bag",
    image: "/images/rice.svg",
    source: "verified",
    price: 86000,
    trend: 1.4,
    trendDirection: "up",
    category: "Grains",
    market: "Agbalata Market Badagry",
    createdAt: "2026-03-28T09:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 111,
    title: "Beans",
    snippet: "Mudu",
    image: "/images/beans.svg",
    source: "verified",
    price: 7500,
    trend: 2.1,
    trendDirection: "up",
    category: "Grains",
    market: "Agbalata Market Badagry",
    createdAt: "2026-03-28T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 112,
    title: "Tomatoes",
    snippet: "Small Basket",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 24000,
    trend: 3.2,
    trendDirection: "down",
    category: "Vegetables",
    market: "Agbalata Market Badagry",
    createdAt: "2026-03-28T11:00:00Z",
    userId: "system",
    status: "Verified",
  },

  // --- Mushin Market ---
  {
    id: 13,
    title: "Plantain",
    snippet: "Large Bunch",
    image: "/images/plantain.jpg",
    source: "crowdsourced",
    price: 4000,
    trend: 15.0,
    trendDirection: "up",
    category: "Tubers",
    market: "Mushin Market",
    createdAt: "2026-03-27T12:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 130,
    title: "Garri",
    snippet: "Paint Bucket",
    image: "/images/garri.svg",
    source: "verified",
    price: 3200,
    trend: 0.5,
    trendDirection: "down",
    category: "Grains",
    market: "Mushin Market",
    createdAt: "2026-03-28T08:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 131,
    title: "Palm Oil",
    snippet: "5L Gallon",
    image: "/images/palmoil.svg",
    source: "verified",
    price: 7500,
    trend: 1.1,
    trendDirection: "up",
    category: "Oil",
    market: "Mushin Market",
    createdAt: "2026-03-28T09:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 132,
    title: "Onions",
    snippet: "Small Basket",
    image: "/images/onions.svg",
    source: "verified",
    price: 8500,
    trend: 2.2,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mushin Market",
    createdAt: "2026-03-28T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 133,
    title: "Crayfish",
    snippet: "Paint Bucket",
    image: "/images/crayfish.jpg",
    source: "verified",
    price: 17500,
    trend: 4.5,
    trendDirection: "up",
    category: "Protein",
    market: "Mushin Market",
    createdAt: "2026-03-28T11:00:00Z",
    userId: "system",
    status: "Verified",
  },

  // --- Aratumi Market ---
  {
    id: 40,
    title: "Tomatoes",
    market: "Aratumi Market",
    price: 38500,
    image: "/images/tomatoes.svg",
    category: "Vegetables",
    createdAt: "2026-04-06T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 41,
    title: "Tomatoes",
    market: "Aratumi Market",
    price: 39000,
    image: "/images/tomatoes.svg",
    category: "Vegetables",
    createdAt: "2026-04-01T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 410,
    title: "Fish",
    market: "Aratumi Market",
    price: 15000,
    image: "/images/fish.jpg",
    category: "Protein",
    snippet: "Large Basket",
    createdAt: "2026-04-07T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 411,
    title: "Garri",
    market: "Aratumi Market",
    price: 3000,
    image: "/images/garri.svg",
    category: "Grains",
    snippet: "Paint Bucket",
    createdAt: "2026-04-07T11:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 412,
    title: "Yam",
    market: "Aratumi Market",
    price: 2500,
    image: "/images/yam.svg",
    category: "Tubers",
    snippet: "Large Tuber",
    createdAt: "2026-04-07T12:00:00Z",
    userId: "system",
    status: "Verified",
  },

  // --- Epe Fish Market ---
  {
    id: 42,
    title: "Tomatoes",
    market: "Epe Fish Market",
    price: 48000,
    image: "/images/tomatoes.svg",
    category: "Vegetables",
    createdAt: "2026-04-07T08:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 43,
    title: "Tomatoes",
    market: "Epe Fish Market",
    price: 47000,
    image: "/images/tomatoes.svg",
    category: "Vegetables",
    createdAt: "2026-04-02T08:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 420,
    title: "Rice",
    market: "Epe Fish Market",
    price: 88000,
    image: "/images/rice.svg",
    category: "Grains",
    snippet: "50kg Bag",
    createdAt: "2026-04-08T09:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 421,
    title: "Beef",
    market: "Epe Fish Market",
    price: 6500,
    image: "/images/beef.jpg",
    category: "Protein",
    snippet: "1kg Fresh Cut",
    createdAt: "2026-04-08T10:00:00Z",
    userId: "system",
    status: "Verified",
  },
  {
    id: 422,
    title: "Vegetable Oil",
    market: "Epe Fish Market",
    price: 13000,
    image: "/images/vegetable-oil.jpg",
    category: "Oil",
    snippet: "5L Gallon",
    createdAt: "2026-04-08T11:00:00Z",
    userId: "system",
    status: "Verified",
  },
];
