export const priceHistory = [
  {
    id: 1,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 45000,
    trend: 8.2,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T08:30:00Z",
  },
  {
    id: 23,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 41500,
    trend: 2.1,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: 24,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 43000,
    trend: 3.6,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-05T09:15:00Z",
  },
  {
    id: 25,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 42000,
    trend: 2.3,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-08T11:30:00Z",
  },
  {
    id: 26,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 46500,
    trend: 10.7,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-12T08:00:00Z",
  },
  {
    id: 27,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 48000,
    trend: 3.2,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-15T14:20:00Z",
  },
  {
    id: 28,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "crowdsourced",
    price: 47000,
    trend: 2.1,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-18T10:45:00Z",
  },
  {
    id: 29,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 44000,
    trend: 6.3,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-22T09:00:00Z",
  },
  {
    id: 30,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 45500,
    trend: 3.4,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-25T08:30:00Z",
  },
  {
    id: 31,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 45000, // Matching your current ID 1 price
    trend: 1.1,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-28T12:00:00Z",
  },
  {
    id: 32,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 43500,
    trend: 3.3,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-04-02T10:00:00Z",
  },
  {
    id: 40,
    title: "Tomatoes",
    market: "Epe Market",
    price: 38500,
    createdAt: "2026-04-06T10:00:00Z",
  },
  {
    id: 41,
    title: "Tomatoes",
    market: "Epe Market",
    price: 39000,
    createdAt: "2026-04-01T10:00:00Z",
  },
  {
    id: 42,
    title: "Tomatoes",
    market: "Jakande Market",
    price: 48000,
    createdAt: "2026-04-07T08:00:00Z",
  },
  {
    id: 43,
    title: "Tomatoes",
    market: "Jakande Market",
    price: 47000,
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: 2,
    title: "Rice",
    snippet: "50kg Bag",
    image: "/images/rice.svg",
    source: "verified",
    price: 82000,
    trend: 5.4,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T09:10:00Z",
  },
  {
    id: 3,
    title: "Garri",
    snippet: "Paint Bucket ~5kg",
    image: "/images/garri.svg",
    source: "crowdsourced",
    price: 3500,
    trend: 3.1,
    trendDirection: "down",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T07:45:00Z",
  },
  {
    id: 4,
    title: "Beans",
    snippet: "Mudu ~3kg",
    image: "/images/beans.svg",
    source: "verified",
    price: 7200,
    trend: 12.0,
    trendDirection: "up",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T10:00:00Z",
  },
  {
    id: 5,
    title: "Palm Oil",
    snippet: "kerosene keg -20l",
    image: "/images/palmoil.svg",
    source: "verified",
    price: 28500,
    trend: 7.8,
    trendDirection: "up",
    category: "Oil",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
  },
  {
    id: 6,
    title: "Onions",
    snippet: "Medium Bag ~10kg",
    image: "/images/onions.svg",
    source: "crowdsourced",
    price: 18000,
    trend: 4.5,
    trendDirection: "down",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
  },
  {
    id: 7,
    title: "Yam",
    snippet: "Per Tuber ~3kg",
    image: "/images/yam.svg",
    source: "verified",
    price: 2800,
    trend: 2.3,
    trendDirection: "up",
    category: "Tubers",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
  },
  {
    id: 8,
    title: "Pepper",
    snippet: "Derica ~1.5kg",
    image: "/images/pepper.svg",
    source: "crowdsourced",
    price: 4500,
    trend: 6.7,
    trendDirection: "up",
    category: "Vegetables",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T06:20:00Z",
  },
  {
    id: 14,
    title: "Wheat",
    snippet: "50kg Bag",
    image: "/images/grains.svg",
    source: "verified",
    price: 42000,
    trend: 1.2,
    trendDirection: "down",
    category: "Grains",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T12:00:00Z",
  },
  {
    id: 15,
    title: "Eggs",
    snippet: "Crate of 30",
    image: "/images/protein.svg",
    source: "verified",
    price: 5500,
    trend: 10.5,
    trendDirection: "up",
    category: "Protein",
    market: "Mile 12 Market",
    createdAt: "2026-03-26T13:00:00Z",
  },

  // --- BODIJA MARKET ---
  {
    id: 9,
    title: "Maize",
    snippet: "Mudu ~2kg",
    image: "/images/grains.svg",
    source: "verified",
    price: 1200,
    trend: 2.1,
    trendDirection: "down",
    category: "Grains",
    market: "Bodija Market",
    createdAt: "2026-03-27T08:00:00Z",
  },
  {
    id: 10,
    title: "Sweet Potatoes",
    snippet: "Small Basket",
    image: "/images/yam.svg",
    source: "crowdsourced",
    price: 5000,
    trend: 1.5,
    trendDirection: "up",
    category: "Tubers",
    market: "Bodija Market",
    createdAt: "2026-03-27T09:00:00Z",
  },
  {
    id: 16,
    title: "Soya Beans",
    snippet: "Mudu ~2kg",
    image: "/images/grains.svg",
    source: "verified",
    price: 2500,
    trend: 3.0,
    trendDirection: "up",
    category: "Grains",
    market: "Bodija Market",
    createdAt: "2026-03-27T10:00:00Z",
  },
  {
    id: 17,
    title: "Plantain Flour",
    snippet: "1kg Pack",
    image: "/images/yam.svg",
    source: "verified",
    price: 3200,
    trend: 0.5,
    trendDirection: "down",
    category: "Tubers",
    market: "Bodija Market",
    createdAt: "2026-03-27T11:00:00Z",
  },
  {
    id: 18,
    title: "Honey",
    snippet: "1L Bottle",
    image: "/images/palmoil.svg",
    source: "crowdsourced",
    price: 6500,
    trend: 2.2,
    trendDirection: "up",
    category: "Oil",
    market: "Bodija Market",
    createdAt: "2026-03-27T12:00:00Z",
  },
  {
    id: 19,
    title: "Melon (Egusi)",
    snippet: "Mudu",
    image: "/images/grains.svg",
    source: "verified",
    price: 4500,
    trend: 1.8,
    trendDirection: "down",
    category: "Grains",
    market: "Bodija Market",
    createdAt: "2026-03-27T13:00:00Z",
  },
  {
    id: 20,
    title: "Dry Fish",
    snippet: "Medium Size",
    image: "/images/protein.svg",
    source: "crowdsourced",
    price: 2000,
    trend: 5.0,
    trendDirection: "up",
    category: "Protein",
    market: "Bodija Market",
    createdAt: "2026-03-27T14:00:00Z",
  },
  {
    id: 21,
    title: "Crayfish",
    snippet: "Large Paint Bucket",
    image: "/images/protein.svg",
    source: "verified",
    price: 18000,
    trend: 9.2,
    trendDirection: "up",
    category: "Protein",
    market: "Bodija Market",
    createdAt: "2026-03-27T15:00:00Z",
  },
  {
    id: 22,
    title: "Charcoal",
    snippet: "Large Bag",
    image: "/images/onions.svg",
    source: "verified",
    price: 9000,
    trend: 0.0,
    trendDirection: "down",
    category: "All",
    market: "Bodija Market",
    createdAt: "2026-03-27T16:00:00Z",
  },

  // --- WUSE MARKET ---
  {
    id: 11,
    title: "Beef",
    snippet: "1kg Fresh Cut",
    image: "/images/protein.svg",
    source: "verified",
    price: 6000,
    trend: 4.2,
    trendDirection: "up",
    category: "Protein",
    market: "Wuse Market",
    createdAt: "2026-03-27T10:00:00Z",
  },
  {
    id: 12,
    title: "Vegetable Oil",
    snippet: "5L Gallon",
    image: "/images/palmoil.svg",
    source: "verified",
    price: 12500,
    trend: 0.5,
    trendDirection: "down",
    category: "Oil",
    market: "Wuse Market",
    createdAt: "2026-03-27T11:00:00Z",
  },

  // --- OJUWOYE MARKET ---
  {
    id: 13,
    title: "Plantain",
    snippet: "Large Bunch",
    image: "/images/yam.svg",
    source: "crowdsourced",
    price: 4000,
    trend: 15.0,
    trendDirection: "up",
    category: "Tubers",
    market: "Ojuwoye Market",
    createdAt: "2026-03-27T12:00:00Z",
  },
];
