export const commodities = [
  {
    id: 1,
    title: "Tomatoes",
    snippet: "Big Basket ~25kg",
    image: "/images/tomatoes.svg",
    source: "verified",
    price: 45000,
    trend: 8.2,
    trendDirection: "down", // >5% drop = negative trend
    createdAt: "2026-03-26T08:30:00Z",
  },
  {
    id: 2,
    title: "Rice",
    snippet: "50kg Bag",
    image: "/images/rice.svg",
    source: "verified",
    price: 82000,
    trend: 5.4,
    trendDirection: "up",
    createdAt: "2026-03-26T09:10:00Z",
  },
  {
    id: 3,
    title: "Garri",
    snippet: "Paint Bucket ~5kg",
    image: "/images/garri.svg",
    source: "crowdsourced",
    price: 3500,
    trend: 3.1,
    trendDirection: "down",
    createdAt: "2026-03-26T07:45:00Z",
  },
  {
    id: 4,
    title: "Beans",
    snippet: "Mudu ~3kg",
    image: "/images/beans.svg",
    source: "verified",
    price: 7200,
    trend: 12.0,
    trendDirection: "up",
    createdAt: "2026-03-26T10:00:00Z",
  },
  {
    id: 5,
    title: "Palm Oil",
    snippet: "kerosene keg -20l",
    image: "/images/palmoil.svg",
    source: "verified",
    price: 28500,
    trend: 7.8,
    trendDirection: "up",
    createdAt: "2026-03-26T06:20:00Z",
  },
  {
    id: 6,
    title: "Onions",
    snippet: "Medium Bag ~10kg",
    image: "/images/onions.svg",
    source: "crowdsourced",
    price: 18000,
    trend: 4.5,
    trendDirection: "down",
    createdAt: "2026-03-26T06:20:00Z",
  },
  {
    id: 7,
    title: "Yam",
    snippet: "Per Tuber ~3kg",
    image: "/images/yam.svg",
    source: "verified",
    price: 2800,
    trend: 2.3,
    trendDirection: "up",
    createdAt: "2026-03-26T06:20:00Z",
  },
  {
    id: 8,
    title: "Pepper",
    snippet: "Derica ~1.5kg",
    image: "/images/pepper.svg",
    source: "crowdsourced",
    price: 4500,
    trend: 6.7,
    trendDirection: "up",
    createdAt: "2026-03-26T06:20:00Z",
  },
];
